# Generated by Django 3.1.2 on 2020-10-08 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(default='', max_length=255)),
                ('company', models.CharField(default='', max_length=255)),
                ('purpose', models.TextField(default='')),
                ('temperature', models.CharField(default='', max_length=255)),
                ('time_scanned', models.CharField(default='', max_length=255)),
                ('visit_pass_number', models.CharField(default='', max_length=255)),
                ('is_quarantined', models.BooleanField(default=False)),
                ('is_contacted', models.BooleanField(default=False)),
                ('has_travelled', models.BooleanField(default=False)),
                ('is_unwell', models.BooleanField(default=False)),
                ('reg_date', models.DateField(default=django.utils.timezone.now)),
                ('acknowledge', models.BooleanField(default=True)),
            ],
        ),
    ]
