# Generated by Django 3.1.2 on 2020-10-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subs',
            new_name='Sub',
        ),
    ]
